name: Create release and add src-test-script.zip asset
on:
  push:
    tags:
      - 'v*'

jobs:
  create-release:
    name: Create release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Create Release
        id: create-release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref_name }}
          release_name: ${{ github.ref_name }}
          body: |
            Changes in this Release
            - First Change
            - Second Change
          draft: true
          prerelease: false
    outputs:
      upload_url: ${{ steps.create-release.outputs.upload_url }}
  deliver-src-test-script:
    name: Deliver src-test-script.zip
    runs-on: ubuntu-latest
    needs: create-release
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Create zip file
        run: |
          cd src
          zip -r src-test-script test -x "test/images/*"
          cd -
      - name: Upload Asset
        id: upload-release-asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.create-release.outputs.upload_url }}
          asset_path: src/src-test-script.zip
          asset_name: src-test-script.zip
          asset_content_type: application/zip
