name: Add assets to published release
on:
  release:
    types: [published]

jobs:
  deliver-src-test-script:
    name: Deliver src-test-script.zip
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Create zip file
        run: |
          cd src
          zip -r src-test-script test -x "test/images/*"
          cd -
      - name: Upload Asset
        id: upload-release-asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: src/src-test-script.zip
          asset_name: src-test-script.zip
          asset_content_type: application/zip
  create-branch:
    name: Create branch and update Download link
    runs-on: ubuntu-latest
    needs: deliver-src-test-script
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Create branch
        run: git checkout -b ${{ github.event.release.tag_name }}
      - name: Udpate Download link in README
        run: |
          search="releases/latest/download"
          replace="releases/download/${{ github.event.release.tag_name }}"
          sed -i "s|${search}|${replace}|" README.md
      - name: Setup git config
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "<>"
      - name: Commit
        run: |
          git add README.md
          git commit -m "Update Download link with tagged asset url"
          git push origin refs/heads/${{ github.event.release.tag_name }}
