name: Create branch from release
on:
  release:
    types: [published]

jobs:
  create-branch:
    name: Create branch and update Download link in README
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Create branch
        run: |
          branch_name="${{github.event.release.tag_name##*v}}"
          git checkout -b ${branch_name}
      - name: Udpate Download link in README
        run: |
          search="releases/latest/download"
          replace="releases/download/${{ github.event.release.tag_name }}"
          sed -i "s|${search}|${replace}|" README.md
      - name: Setup git config
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "<>"
      - name: Commit
        run: |
          git add README.md
          git commit -m "Update Download link with tagged asset url"
          git push origin refs/heads/${branch_name}
