name: "Show github context on status"

on:
  status

jobs:
  show-context:
    runs-on: ubuntu-latest
    steps:
    - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
