name: "Fail status"

on:
  pull_request:
    types: synchronize
    branches:
      - main
jobs:
  fail:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: ouzi-dev/commit-status-updater@v2
      with:
        status: "failure"
